-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 25-11-2022 a las 18:45:59
-- Versión del servidor: 10.5.16-MariaDB-cll-lve
-- Versión de PHP: 7.2.34

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `u528601152_upj`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `participantes_fase_grupos`
--

CREATE TABLE `participantes_fase_grupos` (
  `idParticipante` smallint(6) NOT NULL,
  `nombre` varchar(30) COLLATE utf8mb4_spanish_ci NOT NULL,
  `apellido` varchar(25) COLLATE utf8mb4_spanish_ci NOT NULL,
  `afiliado` int(8) UNSIGNED NOT NULL,
  `grupos1` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos2` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos3` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos4` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos5` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos6` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos7` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos8` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos9` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos10` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos11` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos12` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos13` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos14` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos15` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos16` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos17` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos18` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos19` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos20` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos21` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos22` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos23` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos24` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos25` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos26` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos27` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos28` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos29` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos30` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos31` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos32` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos33` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos34` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos35` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos36` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos37` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos38` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos39` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos40` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos41` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos42` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos43` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos44` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos45` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos46` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos47` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos48` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `codigo` int(10) UNSIGNED NOT NULL,
  `confirmada` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 = false - 1 = true'
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `participantes_fase_grupos`
--

INSERT INTO `participantes_fase_grupos` (`idParticipante`, `nombre`, `apellido`, `afiliado`, `grupos1`, `grupos2`, `grupos3`, `grupos4`, `grupos5`, `grupos6`, `grupos7`, `grupos8`, `grupos9`, `grupos10`, `grupos11`, `grupos12`, `grupos13`, `grupos14`, `grupos15`, `grupos16`, `grupos17`, `grupos18`, `grupos19`, `grupos20`, `grupos21`, `grupos22`, `grupos23`, `grupos24`, `grupos25`, `grupos26`, `grupos27`, `grupos28`, `grupos29`, `grupos30`, `grupos31`, `grupos32`, `grupos33`, `grupos34`, `grupos35`, `grupos36`, `grupos37`, `grupos38`, `grupos39`, `grupos40`, `grupos41`, `grupos42`, `grupos43`, `grupos44`, `grupos45`, `grupos46`, `grupos47`, `grupos48`, `codigo`, `confirmada`) VALUES
(1, 'ARMANDO JOSE', 'ECHARRI', 19754, 'empate', 'empate', 'qatar', 'paises bajos', 'empate', 'qatar', 'empate', 'empate', 'gales', 'estados unidos', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'japon', 'alemania', 'empate', 'belgica', 'belgica', 'empate', 'belgica', 'empate', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'ghana', 'empate', 'empate', 'portugal', 'uruguay', 1668781211, 1),
(2, 'MóNICA CLAUDIA', 'FAHEY', 2653, 'empate', 'empate', 'senegal', 'ecuador', 'ecuador', 'qatar', 'empate', 'empate', 'iran', 'empate', 'estados unidos', 'empate', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'canada', 'suiza', 'brasil', 'camerun', 'empate', 'empate', 'brasil', 'uruguay', 'portugal', 'ghana', 'uruguay', 'portugal', 'uruguay', 1668781656, 1),
(3, 'ALDO ERNESTO', 'MARTIN', 2506, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'empate', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'empate', 'belgica', 'belgica', 'empate', 'empate', 'canada', 'empate', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668783157, 1),
(4, 'JOSE LUIS', 'CANDIA', 42702, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'australia', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'empate', 'belgica', 'marruecos', 'croacia', 'belgica', 'canada', 'camerun', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'ghana', 'corea del sur', 'uruguay', 'empate', 'uruguay', 1668782107, 1),
(5, 'NANCY', 'SILVA', 24398, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'empate', 'dinamarca', 'australia', 'empate', 'dinamarca', 'tunez', 'empate', 'empate', 'costa rica', 'japon', 'alemania', 'empate', 'alemania', 'croacia', 'belgica', 'marruecos', 'empate', 'belgica', 'empate', 'suiza', 'empate', 'serbia', 'empate', 'serbia', 'brasil', 'corea del sur', 'portugal', 'ghana', 'portugal', 'corea del sur', 'uruguay', 1668783700, 1),
(6, 'MóNICA CLAUDIA', 'FAHEY', 2653, 'empate', 'empate', 'qatar', 'ecuador', 'ecuador', 'empate', 'empate', 'empate', 'iran', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'empate', 'suiza', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'uruguay', 1668784026, 0),
(7, 'NICOLAS GUILLERMO', 'ASCHERO', 3057, 'empate', 'empate', 'senegal', 'ecuador', 'ecuador', 'qatar', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'tunez', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'suiza', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'ghana', 'ghana', 'uruguay', 'empate', 'uruguay', 1668784004, 1),
(8, 'MARCELO', 'LUCENTE', 32398, 'empate', 'empate', 'qatar', 'empate', 'senegal', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'iran', 'empate', 'argentina', 'mexico', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'españa', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'empate', 'suiza', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'ghana', 'ghana', 'uruguay', 'empate', 'empate', 1668784384, 0),
(9, 'EDGARDO ANDRES', 'PEJOVICH GIANNETTI', 34336, 'empate', 'empate', 'senegal', 'empate', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'iran', 'empate', 'argentina', 'polonia', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'alemania', 'empate', 'alemania', 'croacia', 'canada', 'belgica', 'canada', 'empate', 'canada', 'camerun', 'serbia', 'serbia', 'brasil', 'serbia', 'brasil', 'corea del sur', 'ghana', 'corea del sur', 'portugal', 'empate', 'uruguay', 1668785052, 1),
(10, 'JOSé RAMóN', 'CORREA', 2000, 'empate', 'empate', 'qatar', 'empate', 'ecuador', 'qatar', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'empate', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'dinamarca', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'alemania', 'empate', 'alemania', 'croacia', 'belgica', 'empate', 'empate', 'belgica', 'marruecos', 'suiza', 'brasil', 'camerun', 'empate', 'suiza', 'brasil', 'uruguay', 'ghana', 'ghana', 'uruguay', 'empate', 'empate', 1668786075, 1),
(11, 'JORGE EDUARDO', 'VIOLA', 6279, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'empate', 'empate', 'belgica', 'croacia', 'belgica', 'empate', 'suiza', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'portugal', 'portugal', 'uruguay', 1668786128, 1),
(12, 'EDGARDO ALBERTO', 'SOTTILARO', 210, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'uruguay', 1668786909, 1),
(13, 'SILVIA BEATRIZ', 'CONTI', 2188, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'mexico', 'empate', 'empate', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'dinamarca', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'japon', 'empate', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'camerun', 'brasil', 'suiza', 'brasil', 'empate', 'portugal', 'empate', 'portugal', 'empate', 'uruguay', 1668787907, 1),
(14, 'JUAN CARLOS', 'PIETROCOLA', 19104, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'paises bajos', 'empate', 'empate', 'iran', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'empate', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'empate', 'empate', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'empate', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'empate', 'uruguay', 'ghana', 'empate', 'empate', 'empate', 'uruguay', 1668789403, 1),
(15, 'DANIEL OMAR', 'ULLOQUE', 336513, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668790375, 1),
(16, 'RODOLFO JULIO', 'BYRNE', 28596, 'empate', 'empate', 'senegal', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'iran', 'inglaterra', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'australia', 'australia', 'dinamarca', 'tunez', 'australia', 'alemania', 'españa', 'costa rica', 'españa', 'españa', 'alemania', 'croacia', 'canada', 'belgica', 'croacia', 'croacia', 'canada', 'camerun', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'ghana', 'ghana', 'uruguay', 'empate', 'uruguay', 1668790500, 1),
(17, 'DANIEL OMAR', 'ULLOQUE', 336513, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668790770, 0),
(18, 'HERNAN', 'COLOMBO', 31337, 'empate', 'empate', 'empate', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'empate', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'serbia', 'empate', 'uruguay', 'portugal', 'corea del sur', 'empate', 'empate', 'empate', 1668791868, 1),
(19, 'ALBERTO HORACIO', 'BELLOTTI', 8752, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'qatar', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'empate', 'dinamarca', 'australia', 'australia', 'empate', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'alemania', 'españa', 'empate', 'croacia', 'empate', 'empate', 'empate', 'belgica', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'corea del sur', 'uruguay', 'empate', 'uruguay', 1668792328, 1),
(20, 'GUSTAVO', 'MATHEU', 26275, 'empate', 'empate', 'qatar', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'estados unidos', 'empate', 'gales', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'arabia saudita', 'dinamarca', 'empate', 'tunez', 'empate', 'francia', 'australia', 'alemania', 'empate', 'japon', 'empate', 'españa', 'costa rica', 'croacia', 'belgica', 'marruecos', 'empate', 'empate', 'canada', 'empate', 'brasil', 'camerun', 'empate', 'suiza', 'empate', 'uruguay', 'empate', 'ghana', 'portugal', 'empate', 'uruguay', 1668792814, 0),
(21, 'RUBEN  OMAR', 'MARIA', 2923, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'empate', 'estados unidos', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'ghana', 'portugal', 'portugal', 'ghana', 1668794849, 1),
(22, 'ALBERTO', 'MAURIZI', 579, 'empate', 'empate', 'qatar', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'iran', 'inglaterra', 'argentina', 'polonia', 'arabia saudita', 'argentina', 'polonia', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'australia', 'japon', 'españa', 'empate', 'alemania', 'japon', 'alemania', 'croacia', 'belgica', 'belgica', 'canada', 'croacia', 'empate', 'suiza', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'portugal', 'corea del sur', 'uruguay', 1668795507, 1),
(23, 'TERESITA', 'HERNANDEZ', 26150, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'tunez', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'empate', 'croacia', 'croacia', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'portugal', 'portugal', 'empate', 1668795181, 1),
(24, 'ALBERTO', 'MAURIZI', 579, 'empate', 'empate', 'qatar', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'iran', 'inglaterra', 'argentina', 'polonia', 'arabia saudita', 'argentina', 'polonia', 'mexico', 'dinamarca', 'australia', 'australia', 'francia', 'tunez', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'japon', 'alemania', 'croacia', 'belgica', 'belgica', 'canada', 'croacia', 'empate', 'suiza', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'portugal', 'corea del sur', 'uruguay', 1668796101, 0),
(25, 'GUSTAVO JORGE', 'JACOBSEN', 2712, 'empate', 'empate', 'qatar', 'empate', 'ecuador', 'empate', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'empate', 'mexico', 'arabia saudita', 'argentina', 'empate', 'arabia saudita', 'tunez', 'empate', 'tunez', 'empate', 'empate', 'dinamarca', 'japon', 'empate', 'empate', 'españa', 'españa', 'alemania', 'croacia', 'empate', 'belgica', 'canada', 'empate', 'marruecos', 'empate', 'brasil', 'serbia', 'brasil', 'suiza', 'empate', 'empate', 'portugal', 'ghana', 'empate', 'corea del sur', 'uruguay', 1668799756, 1),
(26, 'MARIA INES', 'FONTANA', 346128, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'españa', 'españa', 'alemania', 'empate', 'belgica', 'belgica', 'croacia', 'croacia', 'empate', 'suiza', 'brasil', 'camerun', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'empate', 'portugal', 'portugal', 'uruguay', 1668801159, 1),
(27, 'ELISEO', 'ROUGIER', 24021, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'arabia saudita', 'empate', 'argentina', 'empate', 'dinamarca', 'francia', 'australia', 'dinamarca', 'empate', 'australia', 'alemania', 'españa', 'empate', 'españa', 'empate', 'alemania', 'croacia', 'belgica', 'empate', 'croacia', 'belgica', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'empate', 'empate', 'uruguay', 'empate', 'corea del sur', 'empate', 'corea del sur', 'uruguay', 1668801309, 1),
(28, 'NÉSTOR HUGO', 'CENTENO', 18557, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'camerun', 'brasil', 'empate', 'brasil', 'serbia', 'empate', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'uruguay', 1668802530, 1),
(29, 'HéCTOR DANIEL', 'BUSTO', 332682, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'tunez', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'empate', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'empate', 'empate', 'uruguay', 1668803106, 1),
(30, 'HORACIO JORGE', 'SCORDAMAGLIA', 13757, 'empate', 'empate', 'empate', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'gales', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'empate', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668804350, 1),
(31, 'ALBERTO PABLO', 'CARRA', 1432, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'iran', 'estados unidos', 'empate', 'empate', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'empate', 'australia', 'francia', 'francia', 'empate', 'alemania', 'empate', 'costa rica', 'alemania', 'japon', 'alemania', 'empate', 'canada', 'empate', 'empate', 'belgica', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'empate', 'empate', 'uruguay', 'empate', 'uruguay', 1668804788, 1),
(32, 'PQBLO', 'INCHAUSPE', 35179, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'empate', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668807560, 1),
(33, 'SALVADOR NESTOR', 'INTILI', 1421, 'empate', 'empate', 'empate', 'ecuador', 'ecuador', 'empate', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'empate', 'empate', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'camerun', 'brasil', 'empate', 'empate', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668807722, 1),
(34, 'RICARDO', 'DENEGRI', 19900, 'empate', 'empate', 'empate', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'iran', 'gales', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'empate', 'alemania', 'empate', 'alemania', 'croacia', 'canada', 'empate', 'croacia', 'croacia', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'empate', 'corea del sur', 'uruguay', 'empate', 'uruguay', 1668808387, 1),
(35, 'FACUNDO', 'GOWLAND', 43801, 'empate', 'empate', 'qatar', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'gales', 'argentina', 'empate', 'polonia', 'empate', 'argentina', 'mexico', 'dinamarca', 'empate', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'empate', 'empate', 'alemania', 'japon', 'empate', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'canada', 'suiza', 'brasil', 'empate', 'empate', 'suiza', 'brasil', 'empate', 'portugal', 'empate', 'uruguay', 'portugal', 'uruguay', 1668809986, 1),
(36, 'ADOLFO ANTONIO', 'DE NARDO', 12426, 'empate', 'empate', 'empate', 'ecuador', 'ecuador', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'iran', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'empate', 'canada', 'belgica', 'canada', 'empate', 'canada', 'camerun', 'brasil', 'camerun', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'empate', 'uruguay', 'portugal', 'uruguay', 1668810844, 1),
(37, 'JULIO CESAR', 'ZIRPOLI', 279722, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'empate', 'alemania', 'croacia', 'empate', 'belgica', 'croacia', 'empate', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'empate', 'empate', 'uruguay', 'corea del sur', 'uruguay', 1668812700, 1),
(38, 'NOELIA NOEMI', 'HALJAN', 3294, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'empate', 'empate', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'empate', 'españa', 'españa', 'alemania', 'marruecos', 'empate', 'belgica', 'croacia', 'empate', 'empate', 'camerun', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'ghana', 'empate', 'uruguay', 'empate', 'uruguay', 1668814098, 1),
(39, 'JUAN CARLOS', 'IBARRA', 338, 'empate', 'empate', 'empate', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'empate', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'empate', 'dinamarca', 'francia', 'tunez', 'francia', 'empate', 'empate', 'alemania', 'españa', 'japon', 'empate', 'empate', 'empate', 'empate', 'belgica', 'belgica', 'croacia', 'croacia', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'serbia', 'empate', 'uruguay', 'portugal', 'corea del sur', 'empate', 'empate', 'empate', 1668816709, 1),
(40, 'MARIA ESTELA', 'FONTANA', 15383, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'qatar', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'empate', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'empate', 'empate', 'empate', 'alemania', 'marruecos', 'belgica', 'empate', 'empate', 'empate', 'canada', 'camerun', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'uruguay', 'empate', 'uruguay', 1668817450, 1),
(41, 'ROBERTO', 'COLUCCIO', 29202, 'empate', 'empate', 'empate', 'ecuador', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'empate', 'empate', 'francia', 'empate', 'dinamarca', 'empate', 'empate', 'alemania', 'españa', 'costa rica', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'canada', 'suiza', 'brasil', 'serbia', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'ghana', 'portugal', 'portugal', 'uruguay', 1668817976, 0),
(42, 'PABLO HERNAN', 'CARDENAS', 33655, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'empate', 'empate', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668817247, 1),
(43, 'LEONARDO', 'MONTERO', 779164, 'empate', 'empate', 'qatar', 'ecuador', 'ecuador', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'iran', 'inglaterra', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'tunez', 'dinamarca', 'alemania', 'españa', 'costa rica', 'españa', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'canada', 'croacia', 'marruecos', 'camerun', 'brasil', 'serbia', 'brasil', 'suiza', 'brasil', 'uruguay', 'ghana', 'corea del sur', 'portugal', 'portugal', 'uruguay', 1668821635, 1),
(44, 'JORGE OMAR', 'HERRERA', 25487, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'empate', 'empate', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'empate', 'alemania', 'empate', 'belgica', 'empate', 'croacia', 'croacia', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'empate', 'empate', 'uruguay', 'empate', 'ghana', 'portugal', 'portugal', 'empate', 1668821639, 1),
(45, 'ANALIA SUSA', 'PEREA', 3326, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'empate', 'empate', 'argentina', 'empate', 'empate', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'tunez', 'francia', 'tunez', 'australia', 'alemania', 'empate', 'japon', 'empate', 'japon', 'empate', 'croacia', 'empate', 'belgica', 'empate', 'empate', 'canada', 'empate', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'empate', 'uruguay', 'corea del sur', 'uruguay', 1668819261, 1),
(46, 'ADRIANA', 'SALUSSO', 29305, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'mexico', 'polonia', 'empate', 'argentina', 'mexico', 'dinamarca', 'empate', 'australia', 'empate', 'francia', 'empate', 'alemania', 'empate', 'japon', 'alemania', 'españa', 'alemania', 'empate', 'belgica', 'empate', 'croacia', 'empate', 'empate', 'suiza', 'brasil', 'empate', 'empate', 'suiza', 'empate', 'uruguay', 'empate', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668822230, 1),
(47, 'LAURA MARIELA', 'DELGADO', 3250, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'camerun', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668858878, 1),
(48, 'JUAN JOSE', 'SANGIACOMO', 15442, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'tunez', 'francia', 'tunez', 'francia', 'empate', 'dinamarca', 'alemania', 'empate', 'empate', 'alemania', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'empate', 'serbia', 'brasil', 'serbia', 'brasil', 'empate', 'portugal', 'ghana', 'portugal', 'portugal', 'ghana', 1668861438, 1),
(49, 'JUAN JOSE', 'SANGIACOMO', 15442, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'tunez', 'francia', 'tunez', 'francia', 'empate', 'dinamarca', 'alemania', 'empate', 'empate', 'alemania', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'empate', 'serbia', 'brasil', 'serbia', 'brasil', 'empate', 'portugal', 'ghana', 'portugal', 'portugal', 'ghana', 1668862654, 0),
(50, 'HORACIO RAUL', 'ROMERO', 18787, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'empate', 'belgica', 'canada', 'empate', 'empate', 'empate', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'uruguay', 'portugal', 'uruguay', 1668868663, 1),
(51, 'FERNANDO MARCELO', 'ABRUñOSA', 31363, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'empate', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'camerun', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'portugal', 'portugal', 'empate', 1668870162, 1),
(52, 'LUIS ALBERTO', 'DEL VALLE', 1183, 'empate', 'empate', 'empate', 'paises bajos', 'senegal', 'qatar', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'empate', 'argentina', 'polonia', 'polonia', 'empate', 'polonia', 'arabia saudita', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'canada', 'belgica', 'croacia', 'empate', 'empate', 'suiza', 'brasil', 'serbia', 'empate', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'portugal', 'portugal', 'uruguay', 1668872870, 1),
(53, 'LEANDRO', 'PALUMBO', 24677, 'empate', 'empate', 'qatar', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'empate', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668876925, 1),
(54, 'MARTA E.V.', 'VILLANUEVA R DE ROSENFELD', 11207, 'empate', 'empate', 'senegal', 'ecuador', 'senegal', 'qatar', 'empate', 'empate', 'iran', 'estados unidos', 'empate', 'inglaterra', 'argentina', 'empate', 'empate', 'empate', 'argentina', 'empate', 'empate', 'empate', 'empate', 'empate', 'francia', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'croacia', 'empate', 'marruecos', 'empate', 'belgica', 'empate', 'camerun', 'empate', 'serbia', 'suiza', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 1668877790, 1),
(55, 'MARTA E.V.', 'VILLANUEVA R DE ROSENFELD', 11207, 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'empate', 'argentina', 'mexico', 'empate', 'argentina', 'polonia', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'canada', 'empate', 'marruecos', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'empate', 'ghana', 'empate', 'uruguay', 'empate', 'uruguay', 1668878163, 0),
(56, 'LAURA NOEMí', 'CHIARAMONTR', 28716, 'empate', 'empate', 'empate', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'arabia saudita', 'argentina', 'argentina', 'empate', 'tunez', 'australia', 'empate', 'francia', 'empate', 'empate', 'alemania', 'empate', 'japon', 'alemania', 'empate', 'alemania', 'marruecos', 'belgica', 'belgica', 'empate', 'belgica', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'empate', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668878306, 1),
(57, 'LAURA NOEMí', 'CHIARAMONTE', 28716, 'empate', 'empate', 'empate', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'arabia saudita', 'argentina', 'argentina', 'empate', 'tunez', 'australia', 'empate', 'francia', 'empate', 'empate', 'alemania', 'empate', 'japon', 'alemania', 'empate', 'alemania', 'marruecos', 'belgica', 'belgica', 'empate', 'belgica', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'empate', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668878931, 0),
(58, 'SILVIA', 'TOMAINO', 3266, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'españa', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'empate', 'suiza', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668879005, 1),
(59, 'DANIEL ARMANDO', 'D ELIAS', 173509, 'empate', 'empate', 'qatar', 'ecuador', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'españa', 'españa', 'alemania', 'empate', 'canada', 'empate', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'empate', 'brasil', 'suiza', 'empate', 'uruguay', 'empate', 'empate', 'empate', 'portugal', 'uruguay', 1668879446, 1),
(60, 'CáNDIDO GURI', 'BLANCO', 951, 'empate', 'empate', 'qatar', 'ecuador', 'empate', 'qatar', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'empate', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668883222, 1),
(61, 'JULIO', 'GAZZOTTU', 25772, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'empate', 'empate', 'empate', 'gales', 'empate', 'iran', 'gales', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'australia', 'alemania', 'españa', 'costa rica', 'españa', 'españa', 'empate', 'marruecos', 'belgica', 'empate', 'croacia', 'croacia', 'empate', 'camerun', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'empate', 'empate', 'portugal', 'ghana', 1668888493, 1),
(62, 'OSVALDO', 'SANTORUFFO', 2935, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'empate', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'ghana', 'empate', 'portugal', 'uruguay', 1668889156, 1),
(63, 'HUGO', 'RANZUGLIA', 27023, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'australia', 'dinamarca', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'canada', 'empate', 'canada', 'camerun', 'empate', 'serbia', 'brasil', 'serbia', 'brasil', 'empate', 'portugal', 'ghana', 'portugal', 'empate', 'empate', 1668889942, 0),
(64, 'JUAN JOSE', 'ABBIATI', 257192, 'empate', 'empate', 'empate', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'dinamarca', 'tunez', 'empate', 'alemania', 'españa', 'japon', 'españa', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'suiza', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'ghana', 'empate', 'empate', 'uruguay', 1668892394, 1),
(65, 'JUAN CARLOS', 'DIAZ', 146803, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'canada', 'empate', 'croacia', 'empate', 'canada', 'camerun', 'brasil', 'camerun', 'brasil', 'suiza', 'empate', 'empate', 'portugal', 'empate', 'empate', 'portugal', 'ghana', 1668896856, 1),
(66, 'MATIAS MANUEL', 'SANCHEZ', 3147, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'tunez', 'francia', 'empate', 'francia', 'francia', 'australia', 'alemania', 'españa', 'costa rica', 'españa', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'camerun', 'brasil', 'camerun', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'portugal', 'portugal', 'uruguay', 1668897132, 1),
(67, 'HUGO LUIS', 'DENAPOLE', 12060, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'marruecos', 'suiza', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'empate', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668901276, 1),
(68, 'OSCAR ALBERTO', 'GALLI', 2841, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'empate', 'camerun', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'portugal', 'portugal', 'uruguay', 1668907624, 1),
(69, 'GUSTAVO CARLOS', 'TOMAINO', 277088, 'empate', 'empate', 'empate', 'empate', 'ecuador', 'qatar', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'empate', 'empate', 'francia', 'tunez', 'empate', 'francia', 'dinamarca', 'empate', 'españa', 'empate', 'españa', 'españa', 'empate', 'croacia', 'belgica', 'empate', 'canada', 'belgica', 'empate', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'ghana', 'uruguay', 'empate', 'uruguay', 1668910651, 1),
(70, 'LAURA LILIANA', 'BERTRAND', 33199, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'empate', 'empate', 'empate', 'gales', 'estados unidos', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'arabia saudita', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'japon', 'costa rica', 'empate', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'canada', 'empate', 'canada', 'camerun', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668913013, 1),
(71, 'DANTE  CARLOS', 'PALOMBA', 269450, 'empate', 'empate', 'empate', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'portugal', 'portugal', 'uruguay', 1668917458, 1),
(72, 'MARIA GABRIELA', 'RIVAS', 34982, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'empate', 'suiza', 'brasil', 'empate', 'empate', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'empate', 1668952621, 1),
(73, 'MIGUEL ANGEL', 'ZANNI', 799, 'empate', 'empate', 'empate', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'empate', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'suiza', 'empate', 'empate', 'brasil', 'serbia', 'empate', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'uruguay', 1668953032, 1),
(74, 'RICARDO ALBERTO', 'NEGREIRA', 27426, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'iran', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'tunez', 'empate', 'empate', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'empate', 'alemania', 'croacia', 'belgica', 'empate', 'empate', 'belgica', 'marruecos', 'camerun', 'brasil', 'empate', 'brasil', 'serbia', 'empate', 'uruguay', 'empate', 'ghana', 'uruguay', 'empate', 'empate', 1668955285, 1),
(75, 'ANA MARIA', 'RODRIGUEZ', 232866, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'empate', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'empate', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'empate', 'alemania', 'españa', 'japon', 'empate', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'canada', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668957856, 1),
(76, 'PATRICIA', 'BELLA', 3298, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'tunez', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'camerun', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'uruguay', 'portugal', 'uruguay', 1668958463, 1),
(77, 'DANIEL', 'ULLOQUE', 336513, 'empate', 'empate', 'empate', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'empate', 'portugal', 'uruguay', 1668960103, 0),
(78, 'NANCY', 'DASSIEU', 3258, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'empate', 'arabia saudita', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'empate', 'españa', 'japon', 'empate', 'empate', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'camerun', 'brasil', 'camerun', 'brasil', 'serbia', 'empate', 'uruguay', 'portugal', 'corea del sur', 'uruguay', 'empate', 'uruguay', 1668960811, 1),
(79, 'GASTON ENRIQUE', 'PEREZ', 33692, 'empate', 'empate', 'senegal', 'empate', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'belgica', 'canada', 'empate', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'portugal', 'portugal', 'uruguay', 1668962585, 1),
(80, 'VIVIANA ALEJANDTA', 'NORIEGA', 2278, 'empate', 'empate', 'senegal', 'empate', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'dinamarca', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'empate', 'empate', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'empate', 1668960364, 1),
(81, 'HUGO', 'PIETRINI', 2699, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'empate', 'francia', 'francia', 'australia', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'empate', 'empate', 'belgica', 'empate', 'belgica', 'canada', 'suiza', 'brasil', 'empate', 'empate', 'suiza', 'brasil', 'empate', 'portugal', 'empate', 'portugal', 'portugal', 'uruguay', 1668966771, 1),
(82, 'DIEGO', 'RIVADENEYRA', 3045, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'españa', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'marruecos', 'empate', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'empate', 'portugal', 'ghana', 'portugal', 'portugal', 'uruguay', 1668966593, 1),
(83, 'DANIEL', 'GENAISIR', 2447, 'empate', 'empate', 'empate', 'paises bajos', 'senegal', 'empate', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'empate', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'empate', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'empate', 'croacia', 'empate', 'marruecos', 'suiza', 'brasil', 'serbia', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668973339, 1),
(84, 'STELLA MARIS', 'FONTE', 18983, 'empate', 'empate', 'senegal', 'ecuador', 'senegal', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'iran', 'empate', 'argentina', 'empate', 'arabia saudita', 'empate', 'argentina', 'arabia saudita', 'empate', 'francia', 'australia', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'empate', 'belgica', 'empate', 'croacia', 'belgica', 'canada', 'camerun', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'ghana', 'corea del sur', 'uruguay', 'corea del sur', 'ghana', 1668977438, 1);
INSERT INTO `participantes_fase_grupos` (`idParticipante`, `nombre`, `apellido`, `afiliado`, `grupos1`, `grupos2`, `grupos3`, `grupos4`, `grupos5`, `grupos6`, `grupos7`, `grupos8`, `grupos9`, `grupos10`, `grupos11`, `grupos12`, `grupos13`, `grupos14`, `grupos15`, `grupos16`, `grupos17`, `grupos18`, `grupos19`, `grupos20`, `grupos21`, `grupos22`, `grupos23`, `grupos24`, `grupos25`, `grupos26`, `grupos27`, `grupos28`, `grupos29`, `grupos30`, `grupos31`, `grupos32`, `grupos33`, `grupos34`, `grupos35`, `grupos36`, `grupos37`, `grupos38`, `grupos39`, `grupos40`, `grupos41`, `grupos42`, `grupos43`, `grupos44`, `grupos45`, `grupos46`, `grupos47`, `grupos48`, `codigo`, `confirmada`) VALUES
(85, 'MAXIMILIANO', 'LEIVA', 44118, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'paises bajos', 'empate', 'empate', 'iran', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'empate', 'mexico', 'empate', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'empate', 'empate', 'belgica', 'croacia', 'croacia', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'empate', 'empate', 'portugal', 'empate', 1668983984, 1),
(86, 'MIGUEL ANGEL', 'SUAREZ', 495, 'empate', 'empate', 'senegal', 'empate', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'empate', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'empate', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1668985858, 1),
(87, 'VIVIANA .ARIA', 'CLIMENTI', 43860, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'estados unidos', 'estados unidos', 'gales', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'australia', 'australia', 'francia', 'francia', 'australia', 'alemania', 'españa', 'costa rica', 'españa', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'canada', 'camerun', 'brasil', 'camerun', 'brasil', 'suiza', 'brasil', 'uruguay', 'ghana', 'corea del sur', 'uruguay', 'corea del sur', 'uruguay', 1668986475, 1),
(88, 'RUBEN DARIO', 'FERNANDEZ', 3283, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'marruecos', 'camerun', 'brasil', 'camerun', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'corea del sur', 'portugal', 'portugal', 'uruguay', 1668987573, 1),
(89, 'CARLOS ALBERTO', 'LOPEZ', 27916, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'empate', 'empate', 'canada', 'belgica', 'canada', 'croacia', 'empate', 'empate', 'brasil', 'camerun', 'brasil', 'suiza', 'empate', 'uruguay', 'portugal', 'empate', 'uruguay', 'empate', 'empate', 1668987640, 1),
(90, 'GISEL EMILCE', 'FERNANDEZ', 3239, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'españa', 'españa', 'alemania', 'empate', 'belgica', 'belgica', 'empate', 'empate', 'marruecos', 'empate', 'brasil', 'serbia', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'ghana', 'portugal', 'portugal', 'uruguay', 1668989294, 0),
(91, 'JEORDANA', 'HEFFNER', 77792, 'empate', 'empate', 'senegal', 'paises bajos', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'estados unidos', 'estados unidos', 'gales', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'tunez', 'dinamarca', 'francia', 'dinamarca', 'alemania', 'españa', 'empate', 'alemania', 'españa', 'alemania', 'marruecos', 'belgica', 'belgica', 'canada', 'empate', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'corea del sur', 'uruguay', 'empate', 'uruguay', 1668990521, 1),
(92, 'JORGE ROBERTO.', 'ESCALADA', 3323, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'qatar', 'empate', 'empate', 'iran', 'empate', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'empate', 'empate', 'francia', 'empate', 'francia', 'empate', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'empate', 'empate', 'empate', 'belgica', 'croacia', 'croacia', 'marruecos', 'suiza', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'empate', 'empate', 'uruguay', 'empate', 'uruguay', 1668991715, 1),
(93, 'JORGE HORACIO', 'RODRIGUEZ', 2903, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'empate', 'francia', 'empate', 'francia', 'francia', 'empate', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'empate', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'camerun', 'brasil', 'suiza', 'brasil', 'uruguay', 'empate', 'ghana', 'uruguay', 'portugal', 'uruguay', 1668974197, 1),
(94, 'JUAN CARLOS', 'INGENITO', 20943, 'empate', 'empate', 'senegal', 'empate', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'gales', 'argentina', 'mexico', 'empate', 'empate', 'argentina', 'mexico', 'empate', 'australia', 'tunez', 'dinamarca', 'empate', 'empate', 'alemania', 'costa rica', 'japon', 'alemania', 'japon', 'alemania', 'croacia', 'belgica', 'empate', 'canada', 'croacia', 'empate', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'ghana', 'ghana', 'uruguay', 'empate', 'empate', 1668998260, 1),
(95, 'LUIS', 'GALEANO', 18875, 'empate', 'empate', 'qatar', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'empate', 'australia', 'francia', 'francia', 'empate', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'empate', 'camerun', 'brasil', 'empate', 'brasil', 'empate', 'empate', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669038344, 1),
(96, 'BERNARDO JORGE', 'BORDAGARAY', 165743, 'empate', 'empate', 'senegal', 'empate', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'empate', 'empate', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669043702, 1),
(97, 'JORGE JUAN', 'DE FILPO', 2412, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'gales', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'suiza', 'brasil', 'empate', 'brasil', 'empate', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669048349, 1),
(98, 'GUSTAVO CARLOS', 'TOMAINO', 3098, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'empate', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'empate', 'belgica', 'empate', 'croacia', 'belgica', 'canada', 'empate', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'ghana', 'empate', 'uruguay', 'portugal', 'uruguay', 1669048504, 0),
(99, 'GUSTAVO CARLOS', 'TOMAINO', 3098, 'empate', 'empate', 'senegal', 'ecuador', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'empate', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'empate', 'empate', 'dinamarca', 'alemania', 'españa', 'empate', 'empate', 'españa', 'alemania', 'empate', 'belgica', 'empate', 'croacia', 'belgica', 'canada', 'empate', 'brasil', 'camerun', 'brasil', 'empate', 'brasil', 'uruguay', 'ghana', 'empate', 'uruguay', 'portugal', 'uruguay', 1669048763, 0),
(100, 'LILIANA ANDREA', 'LAVORATO', 2678, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'empate', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669053576, 1),
(101, 'LILIANA ANDREA', 'LAVORATO', 2678, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'empate', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669053899, 0),
(102, 'LILIANA ANDREA', 'LAVORATO', 2678, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'canada', 'empate', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669053917, 0),
(103, 'CARLOS DANIEL', 'ORTIZ', 260533, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'empate', 1669055638, 1),
(104, 'OSVALDO', 'SANGUINERI', 19794, 'empate', 'empate', 'empate', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'inglaterra', 'empate', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'dinamarca', 'empate', 'españa', 'japon', 'empate', 'japon', 'alemania', 'empate', 'belgica', 'belgica', 'croacia', 'empate', 'empate', 'empate', 'brasil', 'empate', 'suiza', 'empate', 'camerun', 'empate', 'ghana', 'ghana', 'portugal', 'portugal', 'ghana', 1669059959, 1),
(105, 'MARIA ADRIANA', 'ABOT', 2771, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'empate', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'japon', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'croacia', 'marruecos', 'camerun', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'portugal', 'portugal', 'uruguay', 1669065737, 1),
(106, 'GUSTAVO GUILLERMO', 'HIDALGO', 32297, 'empate', 'empate', 'senegal', 'paises bajos', 'empate', 'paises bajos', 'empate', 'empate', 'empate', 'empate', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'empate', 'francia', 'empate', 'alemania', 'españa', 'japon', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'empate', 'empate', 'empate', 'empate', 'suiza', 'brasil', 'empate', 'empate', 'suiza', 'brasil', 'uruguay', 'portugal', 'ghana', 'empate', 'portugal', 'empate', 1669039002, 1),
(107, 'ALEJANDRO J', 'MARCHESE', 3327, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'empate', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'canada', 'empate', 'brasil', 'empate', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'ghana', 'uruguay', 'portugal', 'uruguay', 1669067548, 1),
(108, 'JORGE', 'RECAITE', 29863, 'empate', 'empate', 'senegal', 'paises bajos', 'senegal', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'mexico', 'polonia', 'argentina', 'empate', 'mexico', 'dinamarca', 'francia', 'australia', 'francia', 'francia', 'dinamarca', 'alemania', 'españa', 'costa rica', 'alemania', 'españa', 'alemania', 'croacia', 'belgica', 'belgica', 'croacia', 'belgica', 'canada', 'empate', 'brasil', 'serbia', 'brasil', 'serbia', 'brasil', 'uruguay', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669067590, 1),
(109, 'PATRICIA', 'BORDAGARAY', 334189, 'empate', 'empate', 'senegal', 'empate', 'ecuador', 'paises bajos', 'empate', 'empate', 'gales', 'inglaterra', 'estados unidos', 'inglaterra', 'argentina', 'polonia', 'polonia', 'argentina', 'argentina', 'mexico', 'dinamarca', 'francia', 'empate', 'dinamarca', 'francia', 'dinamarca', 'alemania', 'españa', 'japon', 'empate', 'japon', 'alemania', 'croacia', 'belgica', 'belgica', 'empate', 'empate', 'canada', 'suiza', 'brasil', 'empate', 'brasil', 'suiza', 'brasil', 'corea del sur', 'portugal', 'empate', 'empate', 'portugal', 'uruguay', 1669068245, 1),
(110, 'JOSE PEDRO', 'PUMA', 26634, 'empate', 'empate', 'qatar', 'paises bajos', 'ecuador', 'qatar', 'empate', 'empate', 'iran', 'inglaterra', 'iran', 'gales', 'argentina', 'mexico', 'arabia saudita', 'argentina', 'argentina', 'mexico', 'dinamarca', 'australia', 'tunez', 'dinamarca', 'empate', 'empate', 'japon', 'costa rica', 'empate', 'españa', 'japon', 'empate', 'marruecos', 'belgica', 'belgica', 'empate', 'belgica', 'marruecos', 'suiza', 'brasil', 'camerun', 'brasil', 'suiza', 'brasil', 'corea del sur', 'portugal', 'corea del sur', 'portugal', 'corea del sur', 'uruguay', 1669072190, 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `resultados_fase_grupos`
--

CREATE TABLE `resultados_fase_grupos` (
  `grupos1` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos2` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos3` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos4` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos5` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos6` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos7` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos8` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos9` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos10` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos11` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos12` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos13` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos14` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos15` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos16` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos17` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos18` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos19` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos20` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos21` varchar(15) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos22` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos23` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos24` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos25` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos26` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos27` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos28` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos29` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos30` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos31` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos32` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos33` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos34` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos35` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos36` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos37` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos38` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos39` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos40` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos41` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos42` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos43` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos44` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos45` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos46` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos47` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL,
  `grupos48` varchar(20) COLLATE utf8mb4_spanish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `resultados_fase_grupos`
--

INSERT INTO `resultados_fase_grupos` (`grupos1`, `grupos2`, `grupos3`, `grupos4`, `grupos5`, `grupos6`, `grupos7`, `grupos8`, `grupos9`, `grupos10`, `grupos11`, `grupos12`, `grupos13`, `grupos14`, `grupos15`, `grupos16`, `grupos17`, `grupos18`, `grupos19`, `grupos20`, `grupos21`, `grupos22`, `grupos23`, `grupos24`, `grupos25`, `grupos26`, `grupos27`, `grupos28`, `grupos29`, `grupos30`, `grupos31`, `grupos32`, `grupos33`, `grupos34`, `grupos35`, `grupos36`, `grupos37`, `grupos38`, `grupos39`, `grupos40`, `grupos41`, `grupos42`, `grupos43`, `grupos44`, `grupos45`, `grupos46`, `grupos47`, `grupos48`) VALUES
('empate', 'empate', 'senegal', 'empate', '', '', 'empate', 'empate', 'iran', '', '', '', 'arabia saudita', 'empate', '', '', '', '', 'empate', 'francia', '', '', '', '', 'japon', 'españa', '', '', '', '', 'empate', 'belgica', '', '', '', '', 'suiza', 'brasil', '', '', '', '', 'empate', 'portugal', '', '', '', '');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `participantes_fase_grupos`
--
ALTER TABLE `participantes_fase_grupos`
  ADD PRIMARY KEY (`idParticipante`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `participantes_fase_grupos`
--
ALTER TABLE `participantes_fase_grupos`
  MODIFY `idParticipante` smallint(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
